/**
 * Gromed API
 * L\'api de gromed contenant tout les endpoints et les définitions des schémas
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Alerte Indisponibilite Presentation DTO
 */
export interface AlerteIndisponibilitePresentationDTO { 
    /**
     * Map des codeCIS avec le stock restant
     */
    alertesIndisponibilites?: { [key: string]: number; };
}

