/**
 * Gromed API
 * L\'api de gromed contenant tout les endpoints et les définitions des schémas
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Les informations générale d\'une commande type
 */
export interface CommandeTypeInfoModel { 
    /**
     * Le nom de la commande type
     */
    name?: string;
    /**
     * le nombre de presentation dans la commande type
     */
    nbProduit?: number;
    /**
     * le montant total de la commande type
     */
    prixTotal?: number;
}

