/**
 * Gromed API
 * L\'api de gromed contenant tout les endpoints et les définitions des schémas
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Les compositions d\'un médicament
 */
export interface CompositionDTOModel { 
    /**
     * Le code de la substance
     */
    codeSubstance?: string;
    /**
     * La dénomination de la substance
     */
    denominationSubstance?: string;
    /**
     * La désignation de l\'élément pharmaceutique
     */
    designationElementPharmaceutique?: string;
    /**
     * Le dosage de la substance
     */
    dosage?: string;
    /**
     * La référence du dosage
     */
    referenceDosage?: string;
    /**
     * La nature du composant
     */
    natureComposant?: string;
}

