/**
 * Gromed API
 * L\'api de gromed contenant tout les endpoints et les définitions des schémas
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * filtres pour la recherche de présentations
 */
export interface Filtres { 
    /**
     * Liste de tous les titulaires de médicaments
     */
    titulaires?: Array<string>;
    /**
     * Liste de toutes les dénomations de substances de médicaments
     */
    substancesDenomitations?: Array<string>;
}

