/**
 * Gromed API
 * L\'api de gromed contenant tout les endpoints et les définitions des schémas
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * DTO représentant une information importante
 */
export interface InfoImportanteModel { 
    /**
     * message de l\'information importante
     */
    message?: string;
    /**
     * lien de l\'information importante
     */
    lien?: string;
}

