/**
 * Gromed API
 * L\'api de gromed contenant tout les endpoints et les définitions des schémas
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * DTO de la livraison
 */
export interface LivraisonModel { 
    /**
     * Date d\'envoie de la livraison
     */
    dateLivraison?: string;
    /**
     * Indique si la livraison est livrée en une fois
     */
    delivered?: boolean;
}

