/**
 * Gromed API
 * L\'api de gromed contenant tout les endpoints et les définitions des schémas
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CompositionDTOModel } from './compositionDTOModel';
import { InfoImportanteModel } from './infoImportanteModel';


/**
 * DTO représentant une présentation détaillée
 */
export interface PresentationDetailModel { 
    /**
     * Code CIS de la présentation
     */
    codeCIS?: string;
    /**
     * Code CIP7 de la présentation
     */
    codeCIP7?: string;
    /**
     * Titre de la présentation
     */
    titre?: string;
    /**
     * Description de la présentation
     */
    description?: string;
    /**
     * Prix de la présentation
     */
    prix?: number;
    /**
     * Stock de la présentation
     */
    stock?: number;
    /**
     * Indique si le médicament est générique
     */
    estGenerique?: boolean;
    /**
     * Indique la forme du médicament
     */
    formePharmaceutique?: string;
    /**
     * Indique le titulaire du médicament
     */
    titulaire?: string;
    /**
     * Indique le taux de remboursement
     */
    tauxRemboursement?: number;
    /**
     * Indique les voies d\'administrations du médicament
     */
    voiesAdministration?: string;
    /**
     * Indique la liste des informations importantes du médicament
     */
    informationsImportantes?: Array<InfoImportanteModel>;
    /**
     * Indique la liste des compositions du médicament
     */
    compositions?: Array<CompositionDTOModel>;
}

