/**
 * Gromed API
 * L\'api de gromed contenant tout les endpoints et les définitions des schémas
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * recap des presentations de la livraison
 */
export interface PresentationRecapCommandeDTO { 
    /**
     * nom de la presentation
     */
    nomPresentation?: string;
    /**
     * quantité de la presentation
     */
    quantite?: number;
}

