/**
 * Gromed API
 * L\'api de gromed contenant tout les endpoints et les définitions des schémas
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * DTO représentant une présentation
 */
export interface PresentationCardModel { 
    /**
     * Code CIS du médicament
     */
    codeCIS?: string;
    /**
     * Code CIP7 de la présentation
     */
    codeCIP7?: string;
    /**
     * Dénomination du médicament
     */
    titre?: string;
    /**
     * Indique si le médicament contient des informations importante
     */
    contientInformation?: boolean;
    /**
     * Prix de la présentation
     */
    prix?: number;
    /**
     * Dénomination de la présentation
     */
    description?: string;
    /**
     * Indique si le médicament est générique
     */
    estGenerique?: boolean;
    /**
     * Indique la forme du médicament
     */
    format?: string;
}

