/**
 * Gromed API
 * L\'api de gromed contenant tout les endpoints et les définitions des schémas
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Donnée utilisateur renvoyé a la connection
 */
export interface UtilisateurModel { 
    /**
     * Email de l\'utilisateur
     */
    email?: string;
    /**
     * Nom de l\'utilisateur
     */
    nom?: string;
    /**
     * Prénom de l\'utilisateur
     */
    prenom?: string;
    /**
     * Nom de l\'établissement de l\'utilisateur
     */
    nomEtablissement?: string;
    /**
     * Nombre de médicaments dans le panier
     */
    nbMedicamentsPanier?: number;
}

